apiVersion: apps/v1
kind: Deployment
metadata:
  name: minizi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minizi
  template:
    metadata:
      labels:
        app: minizi
    spec:
      containers:
      - name: minizi
        image: zion4d/minizi:version2
        imagePullPolicy: Always
        ports:
          - containerPort: 8000

