apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
    spec:
      containers:
      - name: redis-commander
        image: rediscommander/redis-commander:latest
        ports:
          - containerPort: 8081
        env:
          - name: REDIS_HOSTS
            value: "local:redis:6480"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-commander
spec:
  type: NodePort  # Add this line to specify the service type
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001  # Optional: specify a custom NodePort (between 30000-32767)
  selector:
    app: redis-commander
